name: Build assets

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'lib/**/*.ts'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build assets
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js Active LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install dependencies (yarn)
        run: pnpm i
      - name: Build assets
        run: pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./assets
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          # prevent deleting build/test-full-routes.json which will break build:docs
          keep_files: true
      - name: Build docs
        run: pnpm build:docs
